repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0  # Use the latest stable release
    hooks:
      - id: black
        args: ["--line-length", "88"]  # Automatically formats code to 88 characters per line
        language_version: python3.9

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1  # Use the latest stable release
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
        args: ["--max-line-length=88"]  # Ensures Flake8 follows the 88 character limit

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace  # Removes trailing whitespace
      - id: end-of-file-fixer  # Ensures files end with a newline
      - id: check-yaml  # Checks YAML file formatting

  # Mypy hook for type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1  # Use the latest stable release
    hooks:
      - id: mypy
        args: ["--strict"]  # Enable strict type checking (optional, can be customized)
        additional_dependencies: [pydantic, pytest, fastapi, fastapi.responses]

  # # Bandit hook for security checks
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.5  # Use the latest stable release
  #   hooks:
  #     - id: bandit
  #       args: ["-r", "app/"]  # Recursively scan your "app/" directory for security issues
